#! /bin/sh

# Keybindings daemon
sxhkd &

# Launch autostart applications
./autostart.sh

# Set workspaces
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap   0

bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner
bspc config click to focus   true

bspc config normal_border_color   "#404552"
bspc config focused_border_color  "#5294e2"
bspc config presel_feedback_color "#5294e2"
